use_frameworks!

platform :ios, '8.0'

target 'Z3Login_Example' do
  pod 'Z3Login', :path => '../'
  pod 'Z3Network', :path => '../../Z3Network'
  pod 'Z3LocationService', :path => '../../Z3LocationService'
end
