use_frameworks!

platform :ios, '11.0'

target 'Z3Login_Example' do
  pod 'Z3Login', :path => '../'
  pod 'Z3CommonLib', :path => '../../Z3CommonLib'
  pod 'Z3Network', :path => '../../Z3Network'
  #source "/Users/tongwanhua/.cocoapods/repos/myspec"
  pod 'CoordinateTransform', :path => '../../CoordinateTransform'
  pod 'PromiseKit', '~> 1.7'
  pod 'CTMediator', '~> 25'
end
