use_frameworks!

platform :ios, '11.0'

target 'Z3Login_Example' do
  pod 'Z3Login', :path => '../'
  pod 'Z3CommonLib', :path => '../../Z3CommonLib'
  pod 'Z3Network', :path => '../../Z3Network'
end
